name: flutter_vap
description: Is a native plugin for playing alpha video animation
version: 1.1.0
homepage: https://github.com/qq326646683/flutter_vap

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.nell.flutter_vap
        pluginClass: FlutterVapPlugin
      ios:
        pluginClass: FlutterVapPlugin
